#!/usr/bin/env python
"""fortune - artistic inspiration at the terminal."""
import argparse
import datetime
import json
import pathlib
import pathlib
import random
import sys
import textwrap

parser = argparse.ArgumentParser()
parser.add_argument('--comment', default='', help='comment output (e.x. ";; ")')
parser.add_argument('--wrap', type=int, default=0, help='wordwrap length (0 to disable)' )
parser.add_argument('--skip-cache', action='store_true', default=False, help='skip cache, print new random quote' )
parser.add_argument('--clear-cache', action='store_true', default=False, help='clear cache' )
parser.add_argument('--author', type=str, default=None, help='return quote from a specific author (ignores cache)')


def main():
    args = parser.parse_args()

    # check cache
    cache_path = pathlib.Path('~').expanduser() / '.fortune.json'
    cache = Cache(cache_path)

    if any([args.skip_cache, args.clear_cache, args.author]):
        quote = None
    else:
        quote = cache.read()

    if not quote:
        quotes_file = resolve_quotes_file_path()
        quotes = list(load_quotes(quote_file=quotes_file))
        if args.author:
            author_quotes = [q for q in quotes if q[0].lower() == args.author.lower()]
            if author_quotes:  # can't take a random from nothing
                quotes = author_quotes
        quote = random.choice(list(quotes))

    author, quotation = quote
    if args.wrap:
        quotation = textwrap.fill(
            quotation, width=args.wrap, fix_sentence_endings=True,
            break_on_hyphens=True, break_long_words=False,
        )
    output = '"{}"\n  -- {}'.format(quotation, author)
    if args.comment:
        output = comment_output(output=output, prefix=args.comment)
    if not args.skip_cache:
        cache.write(quote)
    print(output)


def comment_output(output, prefix=''):
    return '\n'.join([prefix + line for line in output.splitlines()])


def resolve_quotes_file_path():
    here = pathlib.Path(__file__).resolve().parent
    return here / 'quotes.json'


def load_quotes(quote_file):
    try:
        with open(quote_file, 'r') as f:
            for obj in json.load(f):
                author, quotation = obj
                yield author, quotation
    except FileNotFoundError:
        print('quotes file "{}" not found!'.format(quote_file), file=sys.stderr)
        sys.exit(1)
    except json.decoder.JSONDecodeError:
        print('quotes file "{}" is not valid JSON!'.format(quote_file), file=sys.stderr)
        sys.exit(1)


class Cache:
    def __init__(self, path: pathlib.Path):
        self.path = path

    def read(self):
        """Returns a quote if there is a cache for today, otherwise returns None"""
        if not self.path.is_file():
            return None
        with self.path.open('r') as f:
            data = json.load(f)

        if self.today == data.get('date'):
            return data['quote']

        return None

    def write(self, quote):
        """Cache a quote for today"""
        data = {'date': self.today, 'quote': quote}
        with self.path.open('w') as f:
            json.dump(data, f)

    @property
    def today(self) -> str:
        return datetime.datetime.now().strftime('%Y-%m-%d')



if __name__ == '__main__':
    main()
