local Quote(text='', author='') = (
  assert text != '' : '"text" required!';
  assert author != '' : '"author" required!';

  {
    author: author,
    text: text,
  }
);

local quotes = [
  Quote(text='I have little shame, no dignity - all in the name of a better cause.', author='A.J. Jacobs'),
  Quote(text='If you refuse to be made straight when you are green, you will not be made straight when you are dry.', author='African Proverb'),
  Quote(text='In the depth of winter, I finally learned that within me, there lay, an invincible summer.', author='Albert Camus'),
  Quote(text='If you have behaved badly, repent, make what amends you can and address yourself to the task of behaving better next time.', author='Aldous Huxley'),
  Quote(text='Make no judgements where you have no compassion.', author='Anne McCaffrey'),
  Quote(text='Maybe all one can do is hope to end up with the right regrets.', author='Arthur Miller'),
  Quote(text='How few there are who have courage enough to own their faults, or resolution enough to mend them.', author='Benjamin Franklin'),
  Quote(text='Truth is outside of all patterns.', author='Bruce Lee'),
  Quote(text='Isolation is a self-defeating dream.', author='Carlos Salinas de Gortari'),
  Quote(text='There can be no progress without head-on confrontation.', author='Christopher Hitchens'),
  Quote(text='The mistake is thinking that there can be an antidote to the uncertainty.', author='David Levithan'),
  Quote(text="Sometimes it's necessary to go a long distance out of the way to come back a short distance correctly.", author='Edward Albea'),
  Quote(text='If you do not ask the right questions, you do not get the right answers.', author='Edward Hodnett'),
  Quote(text='Sincerity, even if it speaks with a stutter, will sound eloquent when inspired.', author='Eiji Yoshikawa'),
  Quote(text='Anger as soon as fed is dead -- tis starving makes it fat.', author='Emily Dickinson'),
  Quote(text='Guilt: the gift that keeps on giving.', author='Erma Bombeck'),
  Quote(text='The Lᴏʀᴅ will fight for you while you keep silent.', author='Exodus 14:14'),
  Quote(text='There are many ways of going forward, but only one way of standing still.', author='Franklin D. Roosevelt'),
  Quote(text='By imposing too great a responsibility, or rather, all responsibility, on yourself, you crush yourself.', author='Franz Kafka'),
  Quote(text='We are all in the same boat, in a stormy sea, and we owe each other a terrible loyalty.', author='G.K. Chesterton'),
  Quote(text='Doubt must be no more than vigilance, otherwise it can become dangerous.', author='George C. Lichtenberg'),
  Quote(text='Happiness can exist only in acceptance.', author='George Orwell'),
  Quote(text='Intuition is more important to discovery than logic.', author='Henri Poincare'),
  Quote(text='Some of us think holding on makes us strong, but sometimes it is letting go.', author='Herman Hesse'),
  Quote(text='Cure sometimes, treat often, comfort always.', author='Hippocrates'),
  Quote(text='Our biggest problems arise from the avoidance of smaller ones.', author='James A. Lee Iacocca'),
  Quote(text='In our quest for the answers of life we tend to make order out of chaos, and chaos out of order.', author='Jeffrey Fry'),
  Quote(text="If we knew each other's secrets, what comfort should we find.", author='John Churton Collins'),
  Quote(text='In my opinion, actual heroism, like actual love, is a messy, painful, vulnerable business.', author='John Green'),
  Quote(text="For in the dew of little things the heart finds it's morning and is refreshed.", author='Kahlil Gibran'),
  Quote(text='The master understands that the universe is forever out of control.', author='Lao Tzu'),
  Quote(text='Happiness does not depend on outward things, but on the way we see them.', author='Leo Tolstoy'),
  Quote(text="Stagnation is death. If you don't change, you die. It's that simple. It's that scary.", author='Leonard Sweet'),
  Quote(text="Being president is like being a jackass in a hailstorm. There's nothing to do but to stand there and take it.", author='Lyndon Johnson'),
  Quote(text='Fear has its uses but cowardice has none.', author='Mahatma Ghandi'),
  Quote(text='Resentment is like taking poison and waiting for the other person to die.', author='Malachy McCourt'),
  Quote(text='Sanity and happiness are an impossible combination.', author='Mark Twain'),
  Quote(text='Love is a willingless to sacrifice.', author='Michael Novak'),
  Quote(text='Honesty and transparency make you vulnerable. Be honest and transparent anyway.', author='Mother Teresa'),
  Quote(text="Conscience is the dog that can't bite, but never stops barking.", author='Proverb'),
  Quote(text='Let not a man guard his dignity but let his dignity guard him.', author='Ralph Waldo Emerson'),
  Quote(text='Be here now.', author='Ram Dass'),
  Quote(text='The value of identity is that so often with it comes purpose.', author='Richard R. Grant'),
  Quote(text='Suspicion is a heavy armor and with its weight it impedes more than it protects.', author='Robert Burns'),
  Quote(text='Sooner or later everyone sits down to a banquet of consequences.', author='Robert Louis Stevenson'),
  Quote(text='Seek respect mainly from thyself, for it comes first from within.', author='Steven H. Coogler'),
  Quote(text='In general, pride is at the bottom of all great mistakes.', author='Steven H. Coogler'),
  Quote(text='How weird was it to drive streets I knew so well. What a different perspective.', author='Suzanne Vega'),
  Quote(text='Discontent is the first necessity of progress.', author='Thomas Edison'),
  Quote(text='Trust thyself only, and another shall not betray thee.', author='Thomas Fuller'),
  Quote(text='Truth may sometimes hurt, but delusion harms.', author='Vanna Bonta'),
  Quote(text='Show me another pleasure that is daily and lasts an hour like food.', author='Plato'),
  Quote(text='A bowl of soup speaks to the heart better than any politician.', author='Melina Merkouri'),
  Quote(text='Anybody can cook. But it takes a special person to feed the soul of his guests.', author='Socrates'),
  Quote(text='One cannot think well, love well, sleep well, if one has not dined well.', author='Virginia Woolf'),
  Quote(text="In short, I am convinced, both by faith and experience, that to maintain one's self on this earth is not a hardship but a pastime, if we will live simply and wisely.", author='Henry David Thoreau'),
  Quote(text='Hollywood is hype, New York is talk, Chicago is work.', author='Michael Douglas'),
  Quote(text="You shouldn't put ketchup on your hot dog.", author='Barack Obama'),
  Quote(text='Turn the mundane into the sacred.', author='Phil Jackson'),
  Quote(text='Keep your eye on the spirit, not the scoreboard.', author='Phil Jackson'),
  Quote(text='When in doubt, do nothing.', author='Phil Jackson'),
  Quote(text='The road to freedom is a beautiful system.', author='Phil Jackson'),
  Quote(text='Before enlightenment, chop wood, carry water. After enlightenment, chop wood, carry water.', author='Zen Proverb'),
  Quote(text='Labor disgraces no man; unfortunately you occasionally find men who disgrace labor.', author='Ulysses S. Grant'),
  Quote(text="It's good to be king. Wait, maybe. I think maybe I'm just like a little bizarre little person who walks back and forth.", author='Terry Davis'),
  Quote(text='I have nothing to offer but blood, toil, tears and sweat.', author='Winston Churchill'),
  Quote(text='In painting, you have unlimited power. You have the ability to move mountains. You can bend rivers. But when I get home, the only thing I have power over, is the garbage.', author='Bob Ross'),
  Quote(text="Here's your bravery test!", author='Bob Ross'),
  Quote(text="We don't really know where it goes. We don't really care.", author='Bob Ross'),
  Quote(text="People might look at you a bit funny, but it's okay. Artists are allowed to be a bit different.", author='Bob Ross'),
  Quote(text='Trees cover up a multitude of sins.', author='Bob Ross'),
  Quote(text='You can do anything you want to do. This is your world.', author='Bob Ross'),
  Quote(text='This is the hardest part of this method. If you can do this, you can do anything.', author='Bob Ross'),
  Quote(text='Talk to the tree, make friends with it.', author='Bob Ross'),
  Quote(text='Thou hast made us for thyself, O Lord, and our heart is restless until it finds its rest in thee.', author='Augustine'),
  Quote(text='Tolle, lege: take up and read.', author='Augustine'),
  Quote(text='The truth is not always beautiful, nor beautiful words the truth.', author='Lao Tzu'),
  Quote(text='To understand the limitation of things, desire them.', author='Lao Tzu'),
  Quote(text='When there is no desire, all things are at peace.', author='Lao Tzu'),
  Quote(text='Learning makes a man fit company for himself.', author='Thomas Fuller'),
  Quote(text="Give me 18 inches of daylight. That's all I need.", author='Gale Sayers'),
  Quote(text="Wanna hear a bit of Nord wisdom? You don't really know a woman until you've had a strong drink and a fistfight with her.", author='Uthgerd the Unbroken'),
  Quote(text="Never die easy. Why run out of bounds and die easy? Make that linebacker pay. It carries into all facets of your life. It's okay to lose, to die, but don't die without trying, without giving it your best.", author='Walter Payton'),
  Quote(text="If I'm going to get hit, why let the guy who's going to hit me get the easiest and best shot? I explode into the guy who's trying to tackle me.", author='Walter Payton'),
  Quote(text="When you're good at something, you'll tell everyone. When you're great at something, they'll tell you.", author='Walter Payton'),
  Quote(text='Tough times go away, tough people do not.', author='Walter Payton'),
  Quote(text="I'm not a fan of anything, honestly. Except maybe dogs.", author='Rob Bayerl'),
  Quote(text="When whales fight, the shrimp's back is broken.", author='Korean Proverb'),
  Quote(text='You ask all my teammates, the one thing about Michael Jordan was he never asked me to do something that he didn’t fucking do.', author='Michael Jordan'),
  Quote(text="That’s the sign of a good man, if you can talk shit when it's even score or talk shit when you're behind score. When you're ahead, it's easy to talk.", author='Michael Jordan'),
  Quote(text='Why would I think about missing a shot I haven’t taken?', author='Michael Jordan'),
  Quote(text="You're only a success at the moment you perform a successful act.", author='Phil Jackson'),
  Quote(text="I wanna go out and get my nose broke. I wanna go out and get cut. Something that's gonna really just bring out the hurt - the pain. I wanna feel that.", author='Dennis Rodman'),
  Quote(text="I think I've been looking at this all wrong. [You're not one of the rocks?] I think I'm the sand, man.", author='Richie'),
  Quote(text="I don't know how many years on this earth I got left. I'm gonna get real weird with it. Meanwhile... block the wind, I'm gonna roast this bone.", author='Frank Reynolds'),
  Quote(text='Coaching is real simple to me man. You help players realize their dreams. You help them feed their families. And in turn, you eat.', author='Mike Tomlin'),
  Quote(text='I expect routine catches to be made routinely.', author='Mike Tomlin'),
  Quote(text="Do not blink. If you're a blinker, cut your eyelids off.", author='Mike Tomlin'),
  Quote(text="I don't send messages. I just make moves.", author='Mike Tomlin'),
  Quote(text='I have no message if someone spits in your face. Do what comes natural.', author='Mike Tomlin'),
  Quote(text='The meaning of life is to find your gift.  The purpose of life is to give it away.', author='Pablo Picasso'),
  Quote(text='No block, no rock.', author='Ben Johnson'),
  Quote(text="We didn't come here to play a safe game.  We came here to break them.", author='Ben Johnson'),
];

[[quote.author, quote.text] for quote in quotes]
